# coding: utf-8

# flake8: noqa
"""
    Speech Services API v3.0

    Speech Services API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.component import Component
from swagger_client.models.dataset import Dataset
from swagger_client.models.dataset_kind import DatasetKind
from swagger_client.models.dataset_locales import DatasetLocales
from swagger_client.models.dataset_properties import DatasetProperties
from swagger_client.models.dataset_update import DatasetUpdate
from swagger_client.models.detailed_error_code import DetailedErrorCode
from swagger_client.models.endpoint import Endpoint
from swagger_client.models.endpoint_links import EndpointLinks
from swagger_client.models.endpoint_properties import EndpointProperties
from swagger_client.models.endpoint_properties_update import EndpointPropertiesUpdate
from swagger_client.models.endpoint_update import EndpointUpdate
from swagger_client.models.entity_error import EntityError
from swagger_client.models.entity_reference import EntityReference
from swagger_client.models.error import Error
from swagger_client.models.error_code import ErrorCode
from swagger_client.models.evaluation import Evaluation
from swagger_client.models.evaluation_properties import EvaluationProperties
from swagger_client.models.evaluation_update import EvaluationUpdate
from swagger_client.models.file import File
from swagger_client.models.file_kind import FileKind
from swagger_client.models.file_links import FileLinks
from swagger_client.models.file_properties import FileProperties
from swagger_client.models.health_status import HealthStatus
from swagger_client.models.inner_error import InnerError
from swagger_client.models.links import Links
from swagger_client.models.model import Model
from swagger_client.models.model_copy import ModelCopy
from swagger_client.models.model_deprecation_dates import ModelDeprecationDates
from swagger_client.models.model_file import ModelFile
from swagger_client.models.model_links import ModelLinks
from swagger_client.models.model_manifest import ModelManifest
from swagger_client.models.model_properties import ModelProperties
from swagger_client.models.model_update import ModelUpdate
from swagger_client.models.paginated_datasets import PaginatedDatasets
from swagger_client.models.paginated_endpoints import PaginatedEndpoints
from swagger_client.models.paginated_evaluations import PaginatedEvaluations
from swagger_client.models.paginated_files import PaginatedFiles
from swagger_client.models.paginated_models import PaginatedModels
from swagger_client.models.paginated_projects import PaginatedProjects
from swagger_client.models.paginated_transcriptions import PaginatedTranscriptions
from swagger_client.models.paginated_web_hooks import PaginatedWebHooks
from swagger_client.models.profanity_filter_mode import ProfanityFilterMode
from swagger_client.models.project import Project
from swagger_client.models.project_links import ProjectLinks
from swagger_client.models.project_properties import ProjectProperties
from swagger_client.models.project_update import ProjectUpdate
from swagger_client.models.punctuation_mode import PunctuationMode
from swagger_client.models.service_health import ServiceHealth
from swagger_client.models.status import Status
from swagger_client.models.transcription import Transcription
from swagger_client.models.transcription_properties import TranscriptionProperties
from swagger_client.models.transcription_update import TranscriptionUpdate
from swagger_client.models.web_hook import WebHook
from swagger_client.models.web_hook_events import WebHookEvents
from swagger_client.models.web_hook_links import WebHookLinks
from swagger_client.models.web_hook_properties import WebHookProperties
from swagger_client.models.web_hook_properties_update import WebHookPropertiesUpdate
from swagger_client.models.web_hook_update import WebHookUpdate
